key3 = """
One
Two"""

key2 = """
The quick brown \
  fox jumps over \
    the lazy dog."""

regex2 = '''I [dw]on't need \d{2} apples'''
lines  = '''
The first newline is
trimmed in raw strings.
   All other whitespace
   is preserved.
'''